version: '3.8'
name: smartwalk-routing-engine-dev
services:
  routing-engine:
    image: zhukovdm/smartwalk-routing-engine:v5.24.0
    container_name: smartwalk-routing-engine-dev
    environment:
      REGION_FILE: czech-republic-latest
    ports:
      - 5000:5000
    volumes:
      - ../data/assets/routing-engine:/data
    entrypoint: osrm-routed --max-viaroute-size 1000 --algorithm mld /data/${REGION_FILE}.osrm
    healthcheck:
      test: curl --fail 'http://localhost:5000/route/v1/foot/0,0;0,0' || exit 1
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 2m
networks:
  default:
    name: smartwalk-routing-engine-dev-net
