version: '3.8'
name: smartwalk-database
services:
  database:
    image: mongo:4.4.23
    container_name: smartwalk-database
    ports:
      - 27017:27017
    volumes:
      - ../data/assets/database:/data/db
    healthcheck:
      test: mongo --eval 'db.runCommand({ping:1}).ok' mongodb://localhost:27017/smartwalk --quiet
      interval: 15s
      timeout: 15s
      retries: 10
      start_period: 1m
