FROM osrm/osrm-backend:v5.24.0

# https://stackoverflow.com/q/76094428

RUN sed -i \
  -e 's/deb.debian.org/archive.debian.org/g' \
  -e 's|security.debian.org|archive.debian.org/|g' \
  -e '/stretch-updates/d' /etc/apt/sources.list

RUN apt-get update; apt-get -y install wget
